/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_strlen.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: reclaire <reclaire@student.42mulhouse.f    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/02/22 13:38:25 by reclaire          #+#    #+#             */
/*   Updated: 2025/05/19 18:01:56 by reclaire         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libft_int.h"

#include "libft/bits/asm_utils.h"
#include "libft/bits/extended_aliases.h"

EXTENDED_ALIAS("ft_strlen", 0, (), ())
U64	__ft_strlen_base(const_string s)
{
	U64	i;

	i = 0;
	while (s[i] != '\0')
		i++;
	return i;
}

EXTENDED_ALIAS("ft_strlen", 1, (), ())
U64	__ft_strlen_64(const_string s)
{
	U64 *ptr;

	ptr = (U64 *)s;
	do
	{
		
	} while (0);

	return (U64)(((U8 *) ptr) - ((U8 *)s));
}

U64 ft_strnlen(const_string s, U64 maxlen)
{
	U64	i;

	i = 0;
	while (i < maxlen && s[i] != '\0')
		i++;
	return i;
}

/* Auto-generated by build-aux/extended_aliases.py */

#include "libft/sys/cpuid.h"
#include "libft/sys/xsave.h"
#include "libft/io.h"

#if defined(DEBUG)
static void *__resolved_ft_strlen = NULL;
#endif
static U64 (*resolve_ft_strlen(void))(const_string s)
{

#if !defined(DEBUG)
	void *__resolved_ft_strlen = NULL;
#endif
	struct s_cpuid_flags *cpuid_flags;
	struct s_xcr0_flags os_flags;

	cpuid_flags = ft_cpuid_get_cached_flags();
	ft_xgetbv(0, &os_flags.flags);
	if (1)
		__resolved_ft_strlen = __ft_strlen_base;
	else
		__resolved_ft_strlen = __ft_strlen_64;
	return __resolved_ft_strlen;
}

U64 ft_strlen(const_string s)
    __attribute__((ifunc("resolve_ft_strlen")));

#if defined(DEBUG)
__attribute__((constructor)) static void __debug_ifunc()
{
	ft_printf("ft_strlen:");
	if (__resolved_ft_strlen == __ft_strlen_64)
		ft_printf("__ft_strlen_64\n");
	else
		ft_printf("__ft_strlen_base\n");

}
#endif
