/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   bezier.c                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: reclaire <reclaire@student.42mulhouse.f    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/12/06 16:22:26 by reclaire          #+#    #+#             */
/*   Updated: 2025/05/20 04:16:14 by reclaire         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libft/images.h"

#include "libft/bits/extended_aliases.h"
#include "libft/bits/variants/ft_draw_bezier.h"
#include "libft/bits/variants/ft_draw_line.h"

#include <stdarg.h>

void ft_draw_bezier(t_image *img, t_color col, t_v2 p1, t_v2 p2, t_v2 p3, S32 res, U8 flags, ...)
{
	va_list lst;
	t_iv4 clip_rect;

	/* If we aren't ignoring alpha and color's alpha is 0, ignore */
	if (!(flags & FT_DRAW_FLAG_NO_TRANSPARENCY) && col.a == 0)
		return;

	{ /* Get clip rect */
		clip_rect = ft_image_rect(img);

		va_start(lst, flags);
		if (flags & FT_DRAW_FLAG_CLIP)
		{
			t_iv4 r = va_arg(lst, t_iv4);
			clip_rect = ft_clip_rect_rect(r, clip_rect);
		}
		va_end(lst);
	}

	// TODO: clipping

	if ((flags & FT_DRAW_FLAG_NO_TRANSPARENCY) || col.a == 255)
		__ft_draw_bezier_no_alpha(img, col, p1, p2, p3, res);
	else
		__ft_draw_bezier_alpha(img, col, p1, p2, p3, res);
}

EXTENDED_ALIAS("__ft_draw_bezier_no_alpha", 0, (), ())
void __ft_draw_bezier_no_alpha_base(t_image *img, t_color col, t_v2 p1, t_v2 p2, t_v2 p3, S32 res)
{
	t_v2 prev;
	t_v2 p_on_curve;
	F32 t;

	prev = p1;
	for (S32 i = 0; i < res; i++)
	{
		t = (i + 1.0f) / res;
		p_on_curve = ft_bezier_interp(p1, p2, p3, t);
		__ft_draw_line_no_alpha_base(img, vec2_int(prev), vec2_int(p_on_curve), col);
		prev = p_on_curve;
	}
}

EXTENDED_ALIAS("__ft_draw_bezier_alpha", 0, (), ())
void __ft_draw_bezier_alpha_base(t_image *img, t_color col, t_v2 p1, t_v2 p2, t_v2 p3, S32 res)
{
	t_v2 prev;
	t_v2 p_on_curve;
	F32 t;

	prev = p1;
	for (S32 i = 0; i < res; i++)
	{
		t = (i + 1.0f) / res;
		p_on_curve = ft_bezier_interp(p1, p2, p3, t);
		__ft_draw_line_alpha_base(img, vec2_int(prev), vec2_int(p_on_curve), col);
		prev = p_on_curve;
	}
}

/* Auto-generated by build-aux/extended_aliases.py */

#include "libft/sys/cpuid.h"
#include "libft/sys/xsave.h"
#include "libft/io.h"

#if defined(DEBUG)
static void *__resolved___ft_draw_bezier_no_alpha = NULL;
#endif
static void (*resolve___ft_draw_bezier_no_alpha(void))(t_image *img, t_color col, t_v2 p1, t_v2 p2, t_v2 p3, S32 res)
{

#if !defined(DEBUG)
	void *__resolved___ft_draw_bezier_no_alpha = NULL;
#endif
	struct s_cpuid_flags *cpuid_flags;
	struct s_xcr0_flags os_flags;

	cpuid_flags = ft_cpuid_get_cached_flags();
	ft_xgetbv(0, &os_flags.flags);
	if (1)
		__resolved___ft_draw_bezier_no_alpha = __ft_draw_bezier_no_alpha_base;
	return __resolved___ft_draw_bezier_no_alpha;
}

void __ft_draw_bezier_no_alpha(t_image *img, t_color col, t_v2 p1, t_v2 p2, t_v2 p3, S32 res)
	__attribute__((ifunc("resolve___ft_draw_bezier_no_alpha")));
#if defined(DEBUG)
static void *__resolved___ft_draw_bezier_alpha = NULL;
#endif
static void (*resolve___ft_draw_bezier_alpha(void))(t_image *img, t_color col, t_v2 p1, t_v2 p2, t_v2 p3, S32 res)
{

#if !defined(DEBUG)
	void *__resolved___ft_draw_bezier_alpha = NULL;
#endif
	struct s_cpuid_flags *cpuid_flags;
	struct s_xcr0_flags os_flags;

	cpuid_flags = ft_cpuid_get_cached_flags();
	ft_xgetbv(0, &os_flags.flags);
	if (1)
		__resolved___ft_draw_bezier_alpha = __ft_draw_bezier_alpha_base;
	return __resolved___ft_draw_bezier_alpha;
}

void __ft_draw_bezier_alpha(t_image *img, t_color col, t_v2 p1, t_v2 p2, t_v2 p3, S32 res)
	__attribute__((ifunc("resolve___ft_draw_bezier_alpha")));

#if defined(DEBUG)
__attribute__((constructor)) static void __debug_ifunc()
{
	ft_printf("__ft_draw_bezier_no_alpha:");
	if (__resolved___ft_draw_bezier_no_alpha == __ft_draw_bezier_no_alpha_base)
		ft_printf("__ft_draw_bezier_no_alpha_base\n");
	ft_printf("__ft_draw_bezier_alpha:");
	if (__resolved___ft_draw_bezier_alpha == __ft_draw_bezier_alpha_base)
		ft_printf("__ft_draw_bezier_alpha_base\n");
}
#endif
