/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   line.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: reclaire <reclaire@student.42mulhouse.f    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/12/06 15:22:58 by reclaire          #+#    #+#             */
/*   Updated: 2025/05/22 02:06:22 by reclaire         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libft/images.h"

#include "libft/bits/extended_aliases.h"
#include "libft/bits/variants/ft_draw_line.h"

#include <stdarg.h>

void ft_draw_line(t_image *img, t_iv2 p1, t_iv2 p2, t_color col, U8 flags, ...)
{
	va_list lst;
	t_iv4 clip_rect;

	/* If we aren't ignoring alpha and color's alpha is 0, ignore */
	if (!(flags & FT_DRAW_FLAG_NO_TRANSPARENCY) && col.a == 0)
		return;

	{ /* Get clip rect */
		clip_rect = ft_image_rect(img);

		va_start(lst, flags);
		if (flags & FT_DRAW_FLAG_CLIP)
			clip_rect = ft_clip_rect_rect(va_arg(lst, t_iv4), clip_rect);
		va_end(lst);
	}

	if (p1.y == p2.y)
		ft_draw_line_horizontal(img, p1, p2.x, col, flags & FT_DRAW_FLAG_CLIP, clip_rect);
	else if (p1.x == p2.x)
		ft_draw_line_vertical(img, p1, p2.y, col, flags & FT_DRAW_FLAG_CLIP, clip_rect);
	else
	if (ft_clip_line_rect(&p1, &p2, clip_rect))
	{
		if ((flags & FT_DRAW_FLAG_NO_TRANSPARENCY) || col.a == 255)
			__ft_draw_line_no_alpha(img, p1, p2, col);
		else
			__ft_draw_line_alpha(img, p1, p2, col);
	}
}

EXTENDED_ALIAS("__ft_draw_line_no_alpha", 0, (), ())
void __ft_draw_line_no_alpha_base(t_image *img, t_iv2 p1, t_iv2 p2, t_color col)
{
	S32 dx = ft_abs(p2.x - p1.x), dy = ft_abs(p2.y - p1.y);
	S32 sx = (p1.x < p2.x) ? 1 : -1;
	S32 sy = (p1.y < p2.y) ? 1 : -1;
	S32 err = dx - dy, e2;

	while (TRUE)
	{
		*ft_get_pixel(img, p1.x, p1.y) = col;
		if (p1.x == p2.x && p1.y == p2.y)
			break;

		e2 = 2 * err;
		if (e2 > -dy)
		{
			err -= dy;
			p1.x += sx;
		}
		if (e2 < dx)
		{
			err += dx;
			p1.y += sy;
		}
	}
}

EXTENDED_ALIAS("__ft_draw_line_alpha", 0, (), ())
void __ft_draw_line_alpha_base(t_image *img, t_iv2 p1, t_iv2 p2, t_color col)
{
	t_color *addr;

	S32 dx = ft_abs(p2.x - p1.x), dy = ft_abs(p2.y - p1.y);
	S32 sx = (p1.x < p2.x) ? 1 : -1;
	S32 sy = (p1.y < p2.y) ? 1 : -1;
	S32 err = dx - dy, e2;

	while (TRUE)
	{
		addr = ft_get_pixel(img, p1.x, p1.y);
		*addr = ft_alpha_blend(*addr, col);
		if (p1.x == p2.x && p1.y == p2.y)
			break;

		e2 = 2 * err;
		if (e2 > -dy)
		{
			err -= dy;
			p1.x += sx;
		}
		if (e2 < dx)
		{
			err += dx;
			p1.y += sy;
		}
	}
}

/* Auto-generated by build-aux/extended_aliases.py */

#include "libft/sys/cpuid.h"
#include "libft/sys/xsave.h"
#include "libft/io.h"

#if defined(DEBUG)
static void *__resolved___ft_draw_line_no_alpha = NULL;
#endif
static void (*resolve___ft_draw_line_no_alpha(void))(t_image *img, t_iv2 p1, t_iv2 p2, t_color col)
{

#if !defined(DEBUG)
	void *__resolved___ft_draw_line_no_alpha = NULL;
#endif
	struct s_cpuid_flags *cpuid_flags;
	struct s_xcr0_flags os_flags;

	cpuid_flags = ft_cpuid_get_cached_flags();
	ft_xgetbv(0, &os_flags.flags);
	if (1)
		__resolved___ft_draw_line_no_alpha = __ft_draw_line_no_alpha_base;
	return __resolved___ft_draw_line_no_alpha;
}

void __ft_draw_line_no_alpha(t_image *img, t_iv2 p1, t_iv2 p2, t_color col)
	__attribute__((ifunc("resolve___ft_draw_line_no_alpha")));
#if defined(DEBUG)
static void *__resolved___ft_draw_line_alpha = NULL;
#endif
static void (*resolve___ft_draw_line_alpha(void))(t_image *img, t_iv2 p1, t_iv2 p2, t_color col)
{

#if !defined(DEBUG)
	void *__resolved___ft_draw_line_alpha = NULL;
#endif
	struct s_cpuid_flags *cpuid_flags;
	struct s_xcr0_flags os_flags;

	cpuid_flags = ft_cpuid_get_cached_flags();
	ft_xgetbv(0, &os_flags.flags);
	if (1)
		__resolved___ft_draw_line_alpha = __ft_draw_line_alpha_base;
	return __resolved___ft_draw_line_alpha;
}

void __ft_draw_line_alpha(t_image *img, t_iv2 p1, t_iv2 p2, t_color col)
	__attribute__((ifunc("resolve___ft_draw_line_alpha")));

#if defined(DEBUG)
__attribute__((constructor)) static void __debug_ifunc()
{
	ft_printf("__ft_draw_line_no_alpha:");
	if (__resolved___ft_draw_line_no_alpha == __ft_draw_line_no_alpha_base)
		ft_printf("__ft_draw_line_no_alpha_base\n");
	ft_printf("__ft_draw_line_alpha:");
	if (__resolved___ft_draw_line_alpha == __ft_draw_line_alpha_base)
		ft_printf("__ft_draw_line_alpha_base\n");
}
#endif
