/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   line_vertical.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: reclaire <reclaire@student.42mulhouse.f    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/12/06 15:22:58 by reclaire          #+#    #+#             */
/*   Updated: 2025/05/20 14:41:49 by reclaire         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libft/images.h"

#include "libft/bits/extended_aliases.h"
#include "libft/bits/variants/ft_draw_line_vertical.h"

#include <stdarg.h>

void ft_draw_line_vertical(t_image *img, t_iv2 p1, S32 y2, t_color col, U8 flags, ...)
{
	va_list lst;
	t_iv4 clip_rect;

	/* If we aren't ignoring alpha and color's alpha is 0, ignore */
	if (!(flags & FT_DRAW_FLAG_NO_TRANSPARENCY) && col.a == 0)
		return;

	{ /* Clipping */

		{ /* Get clip rect */
			clip_rect = ft_image_rect(img);

			va_start(lst, flags);
			if (flags & FT_DRAW_FLAG_CLIP)
			{
				t_iv4 r = va_arg(lst, t_iv4);
				clip_rect = ft_clip_rect_rect(r, clip_rect);
			}
			va_end(lst);
		}

		/* Clip rect is invalid, ignore */
		if (clip_rect.x >= clip_rect.z || clip_rect.y >= clip_rect.w)
			return;

		/* If line is completely outside the boundary, ignore */
		if (p1.x < clip_rect.x || p1.x >= clip_rect.z ||
			(p1.y < clip_rect.y && y2 < clip_rect.y) ||
			(p1.y > clip_rect.w && y2 >= clip_rect.w))
			return;

		/* Clip */
		if (p1.y < clip_rect.y)
			p1.y = clip_rect.y;
		if (y2 < clip_rect.y)
			y2 = clip_rect.y;
		if (p1.y > clip_rect.w)
			p1.y = clip_rect.w;
		if (y2 > clip_rect.w)
			y2 = clip_rect.w;
	}

	/* Flip line direction if needed */
	if (p1.y < y2)
	{
		S32 tmp;
		tmp = y2;
		y2 = p1.y;
		p1.y = tmp;
	}

	if ((flags & FT_DRAW_FLAG_NO_TRANSPARENCY) || col.a == 255)
		__ft_draw_line_vertical_no_alpha(img, p1, y2, col);
	else
		__ft_draw_line_vertical_alpha(img, p1, y2, col);
}

EXTENDED_ALIAS("__ft_draw_line_vertical_no_alpha", 0, (), ())
void __ft_draw_line_vertical_no_alpha_base(t_image *img, t_iv2 p1, S32 y2, t_color col)
{
	t_color *ptr;
	S32 ylen;

	ylen = y2 - p1.y;
	ptr = ft_get_pixel(img, p1.x, p1.y);
	for (S32 y = 0; y <= ylen; y++, ptr += img->size.x)
		*ptr = col;
}

EXTENDED_ALIAS("__ft_draw_line_vertical_alpha", 0, (), ())
void __ft_draw_line_vertical_alpha_base(t_image *img, t_iv2 p1, S32 y2, t_color col)
{
	t_color *ptr;
	S32 ylen;

	ylen = y2 - p1.y;
	ptr = ft_get_pixel(img, p1.x, p1.y);
	for (S32 y = 0; y <= ylen; y++, ptr += img->size.x)
		*ptr = ft_alpha_blend(*ptr, col);
}

/* Auto-generated by build-aux/extended_aliases.py */

#include "libft/sys/cpuid.h"
#include "libft/sys/xsave.h"
#include "libft/io.h"

#if defined(DEBUG)
static void *__resolved___ft_draw_line_vertical_no_alpha = NULL;
#endif
static void (*resolve___ft_draw_line_vertical_no_alpha(void))(t_image *img, t_iv2 p1, S32 y2, t_color col)
{

#if !defined(DEBUG)
	void *__resolved___ft_draw_line_vertical_no_alpha = NULL;
#endif
	struct s_cpuid_flags *cpuid_flags;
	struct s_xcr0_flags os_flags;

	cpuid_flags = ft_cpuid_get_cached_flags();
	ft_xgetbv(0, &os_flags.flags);
	if (1)
		__resolved___ft_draw_line_vertical_no_alpha = __ft_draw_line_vertical_no_alpha_base;
	return __resolved___ft_draw_line_vertical_no_alpha;
}

void __ft_draw_line_vertical_no_alpha(t_image *img, t_iv2 p1, S32 y2, t_color col)
	__attribute__((ifunc("resolve___ft_draw_line_vertical_no_alpha")));
#if defined(DEBUG)
static void *__resolved___ft_draw_line_vertical_alpha = NULL;
#endif
static void (*resolve___ft_draw_line_vertical_alpha(void))(t_image *img, t_iv2 p1, S32 y2, t_color col)
{

#if !defined(DEBUG)
	void *__resolved___ft_draw_line_vertical_alpha = NULL;
#endif
	struct s_cpuid_flags *cpuid_flags;
	struct s_xcr0_flags os_flags;

	cpuid_flags = ft_cpuid_get_cached_flags();
	ft_xgetbv(0, &os_flags.flags);
	if (1)
		__resolved___ft_draw_line_vertical_alpha = __ft_draw_line_vertical_alpha_base;
	return __resolved___ft_draw_line_vertical_alpha;
}

void __ft_draw_line_vertical_alpha(t_image *img, t_iv2 p1, S32 y2, t_color col)
	__attribute__((ifunc("resolve___ft_draw_line_vertical_alpha")));

#if defined(DEBUG)
__attribute__((constructor)) static void __debug_ifunc()
{
	ft_printf("__ft_draw_line_vertical_no_alpha:");
	if (__resolved___ft_draw_line_vertical_no_alpha == __ft_draw_line_vertical_no_alpha_base)
		ft_printf("__ft_draw_line_vertical_no_alpha_base\n");
	ft_printf("__ft_draw_line_vertical_alpha:");
	if (__resolved___ft_draw_line_vertical_alpha == __ft_draw_line_vertical_alpha_base)
		ft_printf("__ft_draw_line_vertical_alpha_base\n");
}
#endif
